version: '3.7'

services:
  app:
    image: golang:1.16
    command: >
      bash -c "go install github.com/cosmtrek/air@v1.15.1 &&
              air"
    working_dir: '/app'
    ports:
      - '8080:8080'
    volumes:
      - './:/app:cached'
      - 'gopath:/go'
    environment:
      DATABASE_ADDR: 'mysql:3306'

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '13306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql:cached'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clean-architecture-go
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

volumes:
  gopath:
